# Generated by Django 4.2.13 on 2024-08-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_img',
            field=models.ImageField(blank=True, null=True, upload_to='author_img/', verbose_name='Фото/портрет автора'),
        ),
    ]
