# Generated by Django 4.2.13 on 2024-08-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0002_alter_author_author_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_img',
            new_name='img',
        ),
    ]
