# Generated by Django 4.2.13 on 2024-09-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название книги')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/%Y/%m/%d/', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Скидка в %')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('pages', models.PositiveSmallIntegerField(verbose_name='Страниц')),
                ('binding', models.CharField(max_length=100, verbose_name='Переплёт')),
                ('book_format', models.CharField(blank=True, max_length=100, null=True, verbose_name='Формат')),
                ('isbn', models.CharField(max_length=100, verbose_name='ISBN')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес (гр)')),
                ('age_restrictions', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=3, null=True, verbose_name='Возрастные ограничения')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата внесения в каталог')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения карточки')),
                ('stock', models.PositiveIntegerField(verbose_name='Остаток')),
                ('available', models.BooleanField(default=True)),
                ('author', models.ManyToManyField(related_name='author', to='refs.author', verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='goods.categories', verbose_name='Категория')),
                ('genre', models.ManyToManyField(related_name='genre', to='refs.genre', verbose_name='Жанр')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publisher', to='refs.publisher', verbose_name='Издательство')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='refs.series', verbose_name='Серия')),
            ],
            options={
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
