# Generated by Django 4.2.13 on 2024-09-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_genre_options_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
