# Generated by Django 4.2.13 on 2024-08-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='code',
            field=models.CharField(blank=True, choices=[('25', '25'), ('33', '33'), ('29', '29')], max_length=2, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Номер телефона'),
        ),
    ]
