# Generated by Django 4.2.13 on 2024-08-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_alter_customerprofile_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес 1'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес 2'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='code',
            field=models.CharField(blank=True, choices=[('29', '29'), ('33', '33'), ('25', '25')], max_length=2, null=True, verbose_name='Код мобильного оператора'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='home_index',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Почтовый индекс'),
        ),
    ]
