# Generated by Django 4.2.13 on 2024-08-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_alter_customerprofile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(default='@mail.ru', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
